use HanoiTourism
INSERT [dbo].[tStreet] ([StreetID], [DistrictID], [Name], [Description],
[Latitude], [Longitude]) VALUES 
('D1S031', N'D001', N'Chua Lang', N'Chua Lang Street stretches for 1,000 meters, with a width of 6-8 meters. It runs from Nguyen Chi Thanh Street to Lang Street, passing by Chua Lang. The land originally belonged to Yen Lang Farm, Tong Ha, Vinh Thuan District, which later became part of Thanh Tri District before being transferred to Tu Liem District, a suburban area of Hanoi. Yen Lang Commune (also known as Ke Lang) consists of three hamlets: Thuong, Trung, and Ha, which have now become two wards: Lang Thuong and Lang Ha, under Dong Da District. Chua Lang Street falls within Lang Thuong Ward. Previously known as "Ngo Gieng," it served as the main entrance to Chua Lang. The street was renamed in July 2001. Chua Lang, formally known as Chieu Thien Tu, was constructed during the 12th century, in the reign of Ly Tran Tong (1128-1138), located beside the To River. The temple is revered as the "First Buddhist Temple" of Thang Long (ancient name for Hanoi), boasting beautiful scenery and architectural features.',
21.0237421149106, 105.805169796414),
('D1S032', N'D001', N'Huynh Thuc Khang', N'Huynh Thuc Khang Street is 760 meters long and 10-15 meters wide, running from the intersection of Lang Ha - Thai Ha to Nguyen Chi Thanh Street. This is a newly opened street, created through the filling of ponds and rice fields belonging to Yen Lang Village and partially from Thanh Cong Village. In 1998, the People''s Committee of Hanoi officially named the street Huynh Thuc Khang. It is now located in Lang Ha Ward, Dong Da District. Huynh Thuc Khang (1875 – 1947) was a patriotic Confucian scholar from Tien Phuoc District, Quang Nam Province. He passed the imperial examination in 1904 but chose not to enter official service. He led the Duy Tan Movement in Central Vietnam at the beginning of the 20th century (1907 – 1908). The French colonial authorities exiled him to Con Dao for 13 years. In 1927, he founded the newspaper "Tieng Dan" advocating for freedom and democracy. After the August Revolution in 1945, he served as the Minister of Home Affairs in the Government of the Democratic Republic of Vietnam. During President Ho Chi Minh''s visit to France for negotiations in 1946, he was appointed as the acting President. During the resistance war against the French, he was appointed to the Fifth Interzone and passed away in Quang Ngai.',
21.02022628169, 105.808198224425),
('D1S033', N'D001', N'Phao Dai Lang', N'Phao Dai Lang Street begins from Nguyen Chi Thanh Street, passing through the historical site of Phao Dai Lang, and ends at Lang Street, adjacent to house number 778. This area was originally part of the Yen Lang Farm, Tong Ha, Vinh Thuan District in the past. Later, it became part of Thanh Tri District and then Tu Liem District. It is now situated in Lang Thuong Ward, Dong Da District. The street was given its new name in July 2000. Phao Dai Lang, constructed by the French in 1940, stands on the fields of Lang Trung Village. The fortress is equipped with four 75mm artillery guns. After the August Revolution, it was managed by the People''s Army of Vietnam. On the evening of December 19, 1946, the fortress had the honor of firing the signal shots for the Nationwide Resistance War against the return of French colonial invasion, marking the beginning of Hanoi''s 60 days and nights of resistance. On the morning of December 21, 1946, Phao Dai Lang shot down an enemy aircraft over the skies of the capital, achieving our artillery''s first victory. This historical site was designated as a national heritage site in 1993.',
21.0194373761675, 105.805243383437),
('D1S001', N'D001', N'Kim Ma', N'Kim Ma Street, located in Ba Dinh District, Hanoi, spans 2,500 meters in length and measures 12 - 20 meters in width. It stretches from the intersection of Son Tay Street and Nguyen Thai Hoc Street (near Kim Ma Bus Station) to the intersection of Cau Giay Street and Voi Phuc Street. The length of Kim Ma Street was adjusted in July 1996 according to Resolution No. 51/NQ/HD of the People''s Council of Hanoi, on July 13, 1996. The street traverses the former villages of Kim Ma, Van Phuc, Ngoc Khanh, and Thu Le of Thap Tam Trại, Tong Noi, Vinh Thuan District. In the past, there was a gate called Thanh Bao Gate at the beginning of the street (passing through the territories of Thanh Ninh and Phu Bao villages, merged into Thanh Bao village). Currently, it belongs to Kim Ma and Ngoc Khanh wards, Ba Dinh District, Hanoi. During the French colonial period, Kim Ma Street was only named for the section from the beginning of the street to Kim Son Pagoda at the intersection of Giang Van Minh Street, known as Eight-Roof Street. The section after that was part of National Highway 11: Hanoi - Tay Son (now Route 32). After the peace, Kim Ma Street was extended from the intersection of Kim Son Pagoda, including the final section connecting to Tay Son Street. In the late 1980s, houses were built continuously in the final section, and residents began calling it Ngoc Khanh Street. In 1986, the People''s Council of Hanoi renamed the section from Kim Ma to Giang Vo as Ngoc Khanh Street, and on July 13, 1996, the People''s Council of Hanoi redefined the final section of Kim Ma Street, extending it to the intersection of Giang Vo - Cau Giay Street.',
21.0316285733621, 105.81677354104),
('D1S002', N'D001', N'La Thanh', N'La Thanh Street is 2,500 meters long and 11 meters wide. La Thanh Street is located in Dong Da and Ba Dinh districts, Hanoi. It stretches from the intersection of Cho Dua Market to the Voi Phuc - Cau Giay intersection. Originally part of the southern rampart, the mid-loop of the Dai La Citadel, it runs along the northern bank of the Kim Ngưu River - a branch of the To River. It now traverses the wards of O Cho Dua (Dong Da district), Giang Vo, Thanh Cong, and Ngoc Khanh (Ba Dinh district). The term "La Thanh" generally refers to a noun indicating the ramparts surrounding a smaller citadel or a city within. These names were used in ancient histories (of China and Vietnam) to refer to the ramparts built by the Northern invaders within the territory of present-day Hanoi. The name "La Thanh" appeared before the 8th century: in 767, Truong Ba Nghi constructed La Thanh to a height of only a few steps. In 808, Truong Chau rebuilt La Thanh to a height of 22 steps (about 6.8 meters). In 866, Cao Bien constructed Dai La Thanh, extending for 1,980 truong and 5 steps (approximately 6,139 meters), with a height of 2 truong and 6 steps (about 8 meters). Therefore, throughout the Northern domination period, La Thanh was a general term referring to the ramparts that the Northern rulers built around their administrative center, Tong Binh (now Hanoi).',
21.0239105171944, 105.817816537962),
('D1S003', N'D001', N'Dao Tan', N'Dao Tan Street stretches for 900 meters with a width ranging from 20 to 25 meters. Situated in Ba Dinh District, Hanoi, it runs from Lieu Giai Street to Buoi Street, adjacent to the Daewoo Hotel area. Formerly part of the Thu Le Farm in Thuy Le, Vinh Thuan Commune, Vinh Binh District, now it belongs to Ngoc Khanh Ward, Ba Dinh District. The street was named in January 1998, and in December 2004, it was extended by an additional 700 meters from the Institute of Physics (at the intersection with Nguyen Van Ngoc Street) to Buoi Street. According to the Hong Duc map (drawn in 1490 and subsequent editions) as well as the Hanoi map of 1831, this street was originally part of the northern edge of Linh Lang Lake, also known as Thuy Le Lake, which was filled to create the street. By the 1970s, when Thuy Le Lake extended to Lieu Giai Street, Dao Tan Street remained part of the lake''s northern periphery. Dao Trong Tan (1846 – 1906), also known as Mai Tang, hailed from Vinh Thanh Village, Tuy Phuoc District, Binh Dinh Province. According to the genealogy of the Dao family in Vinh Thinh Village, the family name was Dao Tan, with the middle character being "Dang," indicating Dang Tan. His father was Dao Duc Ngoc, and his mother was Ha Thi Loan. In 1867, during the Đinh Mão year, he obtained a bachelor''s degree and served as the Governor of Nghe An Province. He sympathized with Phan Boi Chau and supported him during the plot to attack Nghe An in 1901. Later, he returned to Hue and served as the Minister of Public Works. He opposed the Nguyen Thanh regime and was subsequently removed from office. Dao Tan had a passion for traditional opera (tuồng) and was a renowned playwright of his time. He made significant contributions to the refinement of tuồng art, editing several valuable works and composing new plays. Additionally, he left behind hundreds of poems and Han Chinese songs, many of which expressed patriotic sentiments and praised the sacrifices of past heroes.',
21.0323385191275, 105.810795998455),
('D1S004', N'D001', N'Buoi', N'Buoi Street, 2,250 meters long and 6 meters wide, stretches from the intersection of Cau Giay, passing through the intersection of Cong Vi, to the end of Hoang Hoa Tham Street (Buoi market). In the past, this was the body of an earth-built wall, part of the outer wall surrounding the ancient capital of Thang Long during the Le Dynasty, referred to by some researchers as the "outer wall." This wall extended from Nhat Tan in the west, running along the banks of West Lake through Buoi market, past Cau Giay, So Crossroads, Vong Crossroads, Trung Hien Crossroads (Cho Mo), to the Red River at Vinh Tuy. On the eastern side, the wall aligns with the Red River dyke. Constructed during the Mac Dynasty (late 16th century) after renovations by Trinh Doanh (mid-18th century). The name Buoi Street was given in October 1986. Today, Buoi Street is located in Ngoc Khanh, Cong Vi wards, Ba Dinh district, and Nghia Do, Cau Giay district. The Buoi area, also known as Ke Buoi, is a place that gathers many villages in the southwest corner of West Lake and the northern bank of the To Lich River, such as Nghia Do, Bai An, Vong Thi, Trich Sai, and Yen Thai of ancient Thang Long. Nghia Do village consists of four villages: Tien Thuong (Tan), Van Long (Dau), Nghia Do (Nghe), and An Phu (established in the 17th century, hence not named in Nom characters). Yen Thai village also includes three villages: Ca village (or Doai), An Tho (Tho), and Dong Xa (Dong). Therefore, Ke Buoi is the collective name for several different villages. The Buoi market itself is located on the land of Ca village - Yen Thai. With a long history, each village in this area has its own rich cultural traditions and heritage.',
21.0322444317115, 105.803869747311),
('D1S005', N'D001', N'Pham Huy Thong', N'Pham Huy Thong Street begins at Nguyen Chi Thanh Street (near the Computer Company) and runs westward around the West Lake to the flower garden at the junction of Cong Chenh with Nguyen Chi Thanh Street. Pham Huy Thong Street is 800 meters long and 5-6 meters wide. Located in Ba Dinh District, Hanoi. The land of Ngoc Khanh village separated from the Giang Vo farm, Total Internal, Vinh Thuan district in the past. Now part of Ngoc Khanh Ward, Ba Dinh District. The street name was newly designated in July 2001. Pham Huy Thong (1916-1988) was a professor, academician, poet, historian, and educator. He hailed from Dao Xa village, An Thi district, Hung Yen province. He obtained a Bachelor of Laws degree in Hanoi (1937), pursued a Ph.D. in Law in France (1942), and a Master''s degree in History - Geography (1944). He worked at the French National Research Center (1944-1950), was proficient in multiple foreign languages, and a member of the French Communist Party (1949). In France, he was active in the overseas Vietnamese community, serving as secretary to President Ho Chi Minh and our delegation to France (1946). He was deported back to Vietnam in 1952 and imprisoned in Saigon for two years. Upon release, he served as Secretary-General of the Saigon-Cholon Peace Movement, was then arrested again and taken to Haiphong, and was liberated in 1955 during the revolution. He held many important positions, including Rector of the University of Education, Director of the Institute of Archaeology, Deputy Chairman of the Vietnam Academy of Social Sciences, Member of the German Academy of Sciences, Secretary-General of the Vietnam Historical Science Association, Chairman of the Hanoi Tourism Association, Member of the Central Committee of the Fatherland Front, Member of the Executive Committee of the World Peace Council, and Deputy of the 2nd and 3rd National Assemblies. He was awarded the Ho Chi Minh Prize in 2000. He was one of the pioneers of the "new poetry" movement, author of numerous volumes of poetry and poetic drama, and proposed research on the Hung Vuong era.',
21.0284661095251, 105.810694155922),
('D3S001', N'D003', N'Nguyen Chi Thanh', N'Nguyen Chi Thanh Street starts from Kim Ma Street (at the intersection near Daewoo Hotel), with one side adjacent to Ngoc Khanh Lake and the other side to Vietnam Television Station. It crosses La Thanh Street and reaches Lang Street, near Trung Kinh Bridge over the To River. Nguyen Chi Thanh Street is 2,000 meters long and 20 meters wide. Located in Dong Da District, Hanoi, Nguyen Chi Thanh Street used to be part of Yen Lang Farm and Nhuoc Cong Ward, Tong Ha Commune, Vinh Thuan District. Now it belongs to Ngoc Khanh and Lang Thuong Wards, Ba Dinh District, and Lang Thuong Ward, Dong Da District. This stretch includes the newly opened Lieu Giai Street (established in 1997) and Lang Trung Street (named in 1986), which are now merged. The street was named in January 1998. Nguyen Chi Thanh (1914-1967) was a Vietnamese People''s Army General, born as Nguyen Vinh in Niem Pho Village, Quang Dien District, Thua Thien Province. He joined the Communist Party of Vietnam in 1937, served as the Party Secretary of Thua Thien Province, and was a delegate to the Tan Trao Conference in 1945. He held various important positions during the resistance against the French and the fight against the United States, contributing significantly to the development of the Vietnamese military. He passed away in Hanoi on July 6, 1967, due to illness.',
21.0227798042255, 105.809677382142),
('D2S001', N'D002', N'Hang Dau', N'Hang Dau street is about 272m long,in Dong Xuan Ward, Hoan Kiem District, Hanoi. With east-west direction, the short street starts from Tran Nhat Duat street to Van Xuan park on Phan Dinh Phung street. Formerly, there were many shops selling all kinds of beans (green beans, soybeans, black beans ...) and soy products (tofu, bean sprouts ...). These all were the harvested products of the people living near Red River bank. In the French colonial period, the street was called “Rue des Graines” by French, which means “streets of grains”. After the August Revolution in 1945, the government decided to restore the old name Hang Dau.
Nowadays, there is no longer any house on Hang Dau street trading beans as they switched their business to other items such as auto sparparts, motorcycles, drugs, mobile phones, and aquarium. What types of stalls selling beans turned to Tran Nhat Duat Street.
The most remarkable relicon the street is Hang Dau Water Tower which locates at the big junction of Hang Dau -Hang Than-Quan Thanh -Phan Dinh Phung- Hang Cot-Hang Giay. In 1894, the water tower was built from scrap stone. The imposing structure looks like a fortress tower with three storey of 19-meter diameter and 25 metre high, under the cone- shaped roof, surrounded by small windows of Gothic style. Next to the water tower, Hang Dau park has a large space with flowers, tree and a big fountain. On the occasion of Tet, florists from Hang Luoc street often brings flower works and spring trees there for selling. It’s a very special beauty of Hanoi on this street.',
21.04052, 105.84855),
('D2S002', N'D002', N'Phung Hung', N'Stretching over 1,250 meters, Phung Hung Street stands as a vibrant and diverse cultural hub in the heart of Hanoi, Vietnam. Situated in Hoan Kiem district, near renowned areas like Hang Ma and Hang Dieu, its strategic location makes it a seamless integration into larger city explorations.
The name "Phung Hung" draws its roots from Vietnam''s rich history, carrying profound memories and spiritual values. According to legend, Phung Hung was a revered king during the reign of An Duong Vuong, contributing significantly to the nation''s construction and defense. Notably, Phung Hung played a crucial role in assisting An Duong Vuong in building the magnificent fortress of Co Loa, one of the architectural wonders of ancient times. His sacrifice and bravery have left an indelible cultural legacy, firmly associating the name Phung Hung with valor and heroism.
Phung Hung Street, echoing this historical resonance, has evolved into an integral part of Hanoi''s cultural heritage. In times gone by, the street was renowned for traditional jewelry shops and lantern stores, painting a vivid picture of the traditional beauty of Hanoi''s residents.
Today, Phung Hung Street not only preserves the charm of yesteryears but also undergoes continuous development and diversification. Traditional stores harmoniously coexist with modern brands, creating a unique shopping experience. Culinary delights are also a highlight, as the street welcomes visitors with the distinctive flavors of Hanoi.
Beyond being a shopping and culinary haven, Phung Hung Street serves as a cultural crossroads, where nearby historical landmarks contribute to a vibrant and unique tableau. As night falls, the street lights up with a dazzling display, inviting both tourists and locals to immerse themselves in a lively and captivating atmosphere.
Phung Hung Street, with its blend of history and modernity, promises a multifaceted experience, encapsulating the beauty of Hanoi''s culture. It stands as a testament to the enduring legacy of Phung Hung, where the past gracefully intertwines with the present.',
21.03466, 105.84568),
('D2S003', N'D002', N'Hang Cot', N'Hàng Cót Street is located in the Old Quarter of Hanoi. During the French colonial period, the street was named Rue Takou. The name "Hàng Cót" has been in use since 1945. In the early 20th century, most residents of this area were engaged in weaving and trading "cót," a type of woven mat made from materials extracted from bamboo and nipa palm.
Today, Hàng Cót Street is situated in Hàng Mã Ward, Hoàn Kiếm District, Hanoi, approximately 0.3 km west of Long Bien Bridge and 1 km northwest of Hoan Kiem Lake. It spans 0.4 km from north to south. The northern end of the street borders Hàng Đậu Flower Garden (formerly known as Vạn Xuân), intersecting with Phan Đình Phùng and Hàng Đậu streets. The southern end meets the intersection of Hàng Mã and Hàng Gà streets. In the middle of the street, an overhead railway crosses, leading to Long Bien Bridge over the Red River.
Hàng Cót was built on land that was once part of the Tân Lập - Tân Khai village in Tiền Túc commune (later renamed Thuận Mỹ), Thọ Xương district. According to a plaque at Thái Cam Pagoda (16 Hàng Gà Street), Tân Lập - Tân Khai village was established in 1822. During that time, the residents primarily worked in weaving and selling cót. Weavers worked on the sidewalk right in front of their homes. Although not a major street in Hanoi, Hàng Cót attracted a relatively dense population due to its convenient location for trade, being close to Long Bien Bridge and Dong Xuan Market.
However, during that era, Hàng Cót was not yet a significant trading street. It consisted of small, modest shops serving the essential needs of the local residents. For a more extensive shopping experience, people would often visit Dong Xuan Market, which was less than 0.1 km away from Hàng Cót.
Today, Hàng Cót Street is not only a place preserving traditional values but also a destination attracting tourists with its diverse shopping and culinary experiences. The street still retains a serene atmosphere, making strolling along it a relaxing and immersive experience in history.',
21.03873, 105.84712),
('D2S004', N'D002', N'Hang Giay', N'Heading North-South direction, with the North end at Hang Dau street and the South end at Dong Xuan street, Hang Giay street has a length of 208m, lying within Dong Xuan ward, Hoan Kiem district. 
In the old days, there were many kinds of paper made by villager of Buoi Village, Cot Village sold on the street. They were: tissue paper, coarse paper, thin paper, china paper,etc. On the facades of ancient houses here, you can still contemplate brand names of famous paper stores made by cement relievo. 
The name “ Hang Giay” started to be used from French colonial time as “Rue de Papier” and after August Revolution, it remained just the same. Long time ago, Hang Giay was initially an old dyke road from Northeast Hanoi . Before 1915, the street didn’t have pavement and trees. Almost all the houses were huts or brick houses with tole roofs. 
The business scene was rather silent with a few houses selling haberdashery stuffs and some herbalists selling traditional medicine. On days with periodic trading sessions at Dong Xuan market, the street become busier than usual with villagers from Buoi village selling papers on both sides of the street, near Hang Khoai junction. 
After 1925, Hang Giay street gradually had more western-style houses of wealthy businessmen. Later, the scope of business expanded to other trades, not only paper. However, the name “Hang Giay” is still a deep mark of reminiscence about a richly traditional craft of Hanoi.',
21.03919, 105.84812),
('D2S005', N'D002', N'Nguyen Thiep', N'Nguyễn Thiếp Street is a 272-meter-long road starting from Nguyen Trung Truc Street, intersecting Hang Dau Street, Gầm Cầu Street, and reaching Hang Khoai Street, continuing from Nguyen Thien Thuat Street in Hoan Kiem District. During the French colonial period, this street was called Rue Duranton. After 1945, it was renamed Nguyen Mau Kien Street. In 1947, it was changed to Nguyen Thiep Street.
This street was built on the ancient land that originally belonged to Phuc Lam village, part of To Tuc commune (later changed to Tổng Phúc Lâm), Tho Xuong district. At house number 27, there is the Bà Móc Pagoda, where a stele was engraved in 1795, during the fourth year of Canh Thinh. At house number 2 Gầm Cầu, there is also a temple from Phuc Lam village. In the Le Dynasty, when the Red River was still inside the dike, there was a pier in this area called Bến Bà Móc, named after the pagoda.
The street is named after Nguyen Thiep (1723 - 1804), also known as Khai Xuyen, with the pen name La Son Phu Tu. He hailed from Nguyet Ao village, La Son district, now part of Can Loc district, Ha Tinh province. Nguyen Thiep passed the Hương Cống examination, served as an official in the Tri district, and worked as an education director for 12 years. Later, he retreated to live in Thien Nhan Mountain. He was consulted by King Quang Trung for military strategies against the Qing army, and he was appointed as the head of the Sung Chinh Institute, responsible for translating Confucian classics and converting Han scripts to Nom scripts. Simultaneously, he was authorized to study plans for building a new capital in Nghe An. Despite being invited to serve in the Nguyen dynasty after the collapse of the Tay Son regime, he declined the offer. Nguyen Thiep passed away in 1804.',
21.04017, 105.8494),
('D2S006', N'D002', N'Gam Cau', N'Phố Gầm Cầu stretches nearly 400 meters, running from Trần Nhật Duật Street to Phùng Hưng Street. Situated along the base of Long Biên Bridge, the street takes its name from the bridge''s arched spans, known as "gầm cầu" in Vietnamese.
Originally part of Phúc Lâm village, in the former Tả Túc district (later renamed Phúc Lâm district), and Phủ Từ village, in the former Hậu Túc district (later renamed Đồng Xuân district), both belonging to the old Thọ Xương province. The Phủ Từ communal house was located at 19 Hàng Lược Street, and the Phúc Lâm Pagoda was situated at 120 Yên Phụ Street. Phúc Lâm village became the subject of Cao Bá Quát''s poem "Phúc Lâm lão," reflecting the hardships faced by the local population during the mid-19th century.
During the French colonial period, the street was named Rue Leblanc. After the revolution, it was renamed Khúc Hạo. In 1947, the street was divided into two sections: Nguyễn Hữu Huân from Trần Nhật Duật to Hàng Giấy and Gầm Cầu from Hàng Giấy to Phùng Hưng. In June 1961, both sections were merged, and the street was officially named Gầm Cầu.
This century-old street holds a unique charm distinct from other streets in Hanoi, with a rich history of name changes. During the French colonial era, it was called Rue Leblanc, later changed to Khúc Hạo in 1946. From 1948 to 1954, during the temporary occupation, the street was divided into Nguyễn Hữu Huân in the east and Gầm Cầu in the west. After 1954, it was collectively known as Gầm Cầu, named for its location under the Long Biên Bridge, guiding the railway onto the bridge.
Gầm Cầu Street can be divided into three sections:
The first section, from Phùng Hưng to the intersection at the bottom of Long Biên Bridge, is characterized by narrow pathways, rough stone surfaces, and a dirty roadside. This area serves as a residence for the impoverished.
The second section, from Hàng Giấy to Nguyễn Thiếp, is different with stone-paved surfaces, relatively wider paths, and roofing overhanging the arches below the bridge. Many families live in the arches, creating a unique living space.
The third section, from the intersection at Nguyễn Thiếp to Bờ Sông Street, is a short stretch featuring the Phúc Lâm communal house with a large triple gate facing the riverbank. There are few other houses along this part of the street.
On the odd-numbered side heading south, nestled between the Hang Đậu houses, are small one-story residences. Two notable larger houses with mezzanines (numbers 7 and 13) at the beginning of Hàng Khoai connect to the wall of the Huyền Thiên Temple.
Despite its location under the bridge, with the railway "hanging" above, what makes Gầm Cầu truly unique is the absence of sidewalks. The street is narrow, with some parts only 1.5 meters wide. Daily life and activities on Gầm Cầu present a distinctive scene, unlike any other street in Hanoi. Due to its narrowness, Gầm Cầu is almost exclusively for pedestrians, with very few vehicles passing through.
At the end of the street, there is a path leading up to Long Biên Station, providing access to Long Biên Bridge. This little-known pathway is seldom visited by locals. While the odd-numbered side of Gầm Cầu is cramped with tightly packed shops, the even-numbered side is more spacious, serving as a parking area and hosting some eateries.
Despite its limited recognition on tourist maps, Gầm Cầu Street is a worthwhile destination for visitors exploring Hanoi.',
21.03955, 105.8488),
('D2S007', N'D002', N'Tran Nhat Duat', N'Trần Nhật Duật Street stretches over 800 meters, extending from Yên Phụ Street under the Long Biên Bridge in the southeast direction to the beginning of Chương Dương Bridge, connecting with Trần Quang Khải Street. The street spans across four wards within Hoàn Kiếm District, Hanoi: Đồng Xuân, Hàng Buồm, Phúc Tân, and Lý Thái Tổ, located over 400 meters north of Hoàn Kiếm Lake.
Named after the accomplished scholar and military leader Chiêu Văn Vương Trần Nhật Duật (1255 – 1331), the sixth son of King Trần Thái Tông, the street holds historical significance. Known for his proficiency in literature, martial arts, and multiple foreign languages, Trần Nhật Duật played a crucial role in Vietnamese history. His strategic brilliance was evident during battles against Mongol invasions, contributing to the protection of the nation.
Trần Nhật Duật effectively commanded forces during the defense of Tuyên Quang in 1285, orchestrating a successful strategic retreat to Thiên Trường (former Nam Định) when facing a Southern invasion. His notable contributions include the pivotal role in the Battle of Hàm Tử Quan and the liberation campaign of Thăng Long.
A street named after Trần Nhật Duật, previously known as Bờ Sông (Riverside), weaves through the territory of former villages Nguyên Khiết (Upper and Lower), Trừng Thanh (Middle and Lower), and Hương Bài in the ancient district of Tả Túc (later renamed Phúc Lâm), Thọ Xương Province. Many landmarks, such as Phúc Lâm Pagoda and Hương Bài Communal House, retain traces of this history. Nguyên Khiết Upper Village is also the birthplace of Nguyễn Đình Cáp, the author of the nom poetry story "Quan Âm Thị Kính."
Initially, the first half of the street was referred to as Hàng Nâu, extending from Hàng Đậu Street adjacent to Bến Nứa to the Long Biên Bridge, intersecting with Hàng Khoai, Cao Thắng, and Ô Quan Chưởng Streets. The second half ran from Chợ Gạo Market to Trần Quang Khải Street, crossing the former Cột Đồng Hồ Square and connecting with Hàng Chĩnh, Lương Ngọc Quyến, Hàng Muối, and Nguyễn Hữu Huân Streets today. In the Lê Dynasty era, near this location, Mỹ Lộc Gate opened to the riverbank and Cầu Cháy Wharf, where ferries crossed the Nhị Hà River.
Following the French occupation of Hanoi, the colonial authorities constructed the Thương Chính Market Hall on Bờ Sông Street to regulate and tax goods transported by water through the Tô Lịch River (Chợ Gạo) and Đông Hà Gate (Ô Quan Chưởng). Additionally, the French established a significant structure known as Quai Clémenceau on this street, commonly referred to by locals as the "Trường Ke" (pronounced "Quai" in French, meaning "quay"). This structure is now home to the Trần Nhật Duật Elementary School at 4 Chợ Gạo Street.',
21.03793, 105.85247),
('D2S008', N'D002', N'Hang Luoc', N'Phố Hàng Lược, stretching 264 meters in length and 8 meters in width, runs from Hàng Cót Street to Hàng Mã Street. Originally part of the Phủ Từ and Vĩnh Trù hamlets in the Hậu Túc district (later changed to Đồng Xuân district), Thọ Xương province in the past, it was known as Hàng Lược until 1901.
In 1901, the City Council decided to rename it Sông Tô Lịch with the rationale that "this street was partly built on the location of the ancient Tô Lịch River that used to flow through here," a river "frequently mentioned in Vietnamese stories and songs." The City Council believed that "changing the street name would help preserve a geographical name gradually disappearing from Hanoi''s maps." In 1945, the street was renamed Hàng Lược – Sông Tô Lịch, then in 1949, it became Sông Tô Lịch, and in 1951, it reverted to its original name, Phố Hàng Lược.
Despite its historical association with hairbrush and comb manufacturing during the Lê and early Nguyễn dynasties, by the 20th century, there were no more such establishments on Hàng Lược Street. Consequently, it came to be known as Cống Chéo – Hàng Lược, a complex name.
However, the street is renowned for one specific item that appears only once a year – flowers. Every year, from the Lunar New Year until the 30th day of Tet (the Kitchen Gods'' Day), a flower market gathers on Hàng Lược Street.
Before the establishment of Đồng Xuân Market, there was only Cầu Đông Market. This market operated on both banks of the Tô River, now located at the beginning of Hàng Đường Street. Flowers were also sold here. During the French colonial period, this market was dismantled to build Đồng Xuân Market, and the flower market relocated to the last market on Hàng Khoai Street. Around 1910-1915, unable to accommodate the growing variety and quantity of Tet flowers, the market moved to Hàng Lược Street. The Hàng Lược Flower Market flourished, becoming an annual tradition. Even during the fierce anti-American years, the flower market dispersed to Đường Thành Street, but Hàng Lược still featured flowers. In 1947, during the Đinh Hợi Tet, when Hanoi was a battleground, the flower market didn''t convene, but flowers from Nhật Tân and Quảng Bá still made their way to the western frontlines of Liên khu I. It became a gesture of solidarity and support for the soldiers defending the capital.
Even during the most intense years of the anti-American resistance, when the flower market was partially relocated to Đường Thành Street, Hàng Lược still showcased flowers. There was even a Tet when the Vietnamese government allowed released American pilots to visit the Hàng Lược Flower Market before they returned home, showcasing the refined and elegant cultural life of the heroic capital city.',
21.03782, 105.84791),
('D2S009', N'D002', N'Hang Chai', N'Hang Chai Street is an 85-meter-long thoroughfare stretching from Hang Ruoi Street to Hang Cot Street in the northern part of Hanoi''s Old Quarter. Originally part of Tan Khai village in the former Tien Tuc district (later changed to Thuan My), it was situated in the Tho Xuong district.
The name "Hang Chai" has its origins in the fact that the street used to be home to numerous shops selling bottles, jars, and tea bags. Additionally, it was known by another name, "Ngo Ngang Street." During the French colonial period, the French referred to it as "ruelle Ngo Ngang" (crossroad alley). Since 1945, the street has officially been named Hang Chai.
Few people know that Hang Chai Street was once associated with a traditional art form of ancient Thang Long, the capital city. This art form was known as the "hát ả đào" singing profession. Up until the 1930s, there was still a temple dedicated to the hát ả đào profession behind house number 7 on the street.
Legend has it that the founders of this profession were a couple named Dinh Du from Thanh Hoa, who migrated to Thang Long and settled in Lo Khe village, now part of Lien Ha commune in Dong Anh district, on the outskirts of Hanoi. The main temple was located in Lo Khe village, while the temple in Hang Chai served as a place for worship.
During the active period of the temple in Hang Chai, every annual profession worshiping ceremony attracted hat a dao singers who gathered to sing sacred songs and perform traditional dances, creating a lively atmosphere along the street. However, with the changes of time, the temple in Hang Chai no longer exists.
At the intersection of Hang Chai and Hang Cot Streets stands Thanh Quan Secondary School, another historical site related to the singing profession. In 1887, a Chinese merchant constructed the first Tuong (classical opera) theater in Hanoi at this location. In 1916, the theater was demolished to make way for a school.
Today, Hang Chai Street is one of the narrowest and shortest streets in Hanoi''s Old Quarter. Though referred to as a "street," the space here is cramped, resembling more of an alley.
Situated in a prime location for trading activities, life on Hang Chai Street remains vibrant with bustling eateries and street vendors catering to passersby. Despite still bearing the name Hang Chai, the street no longer sells bottles and jars as it did in the past. Instead, the characteristic goods sold today are artificial flowers, with shops concentrated in the section near Hang Ruoi Street.',
21.03747, 105.84763),
('D2S010', N'D002', N'Hang Khoai', N'Hang Khoai Street, measuring 360 meters in length, stretches from the foot of Long Bien Bridge, along Tran Nhat Duat Street, to Hang Luoc Street. This area was originally part of Huyen Dieu village in Hien Tuc district (later changed to Dong Xuan district) during the Nguyen dynasty.
During the French colonial period, the street was named "Rue der Tubercules," which translates to the street of tubers. It served as a marketplace specializing in the sale of various vegetables and tubers from northern provinces, as well as suburban areas of Hanoi, ferried across the middle of the Red River.
During the Vietnam War, when Long Bien Bridge was heavily bombarded, Hang Khoai found itself in a critical target zone. As a result, the local residents evacuated, leaving the streets eerily deserted.
Amidst the street, at number 54, stands the ancient Huyen Thien Temple, dedicated to Huyen Thien Tran Vu (a revered deity worshipped at Quan Thanh Temple). Also known as Chua Huyen Thien, the temple''s wall next to the roof bears the inscription "Huyen Thien Co Quan."
With the country''s development and the capital''s growth, Hang Khoai has transformed into a street densely packed with eateries and vendors. Strolling along Hang Khoai, visitors might feel as if they are at home, surrounded by familiar daily items: a red wooden cutting board, a ginger-grinding pestle, vibrant turmeric, a shiny stainless steel grilling tray, or a stack of notebooks beside a box of ballpoint pens "Miss Wine" for this evening. A set of seven shiny bowls and plates, stylishly arranged, awaits the upcoming birthday party. And that crystal clear glass set is simply exquisite! It perfectly complements the liquor cabinet at home...
Like other markets, as night falls, Hang Khoai "never sleeps." Starting from 10:00 PM, the street becomes lively with vendors and carts transporting vegetables from Dong Anh, Da Lat, and China, gathering along its length. Sparkling under the lights are plump white turnips, vibrant red tomatoes and carrots, and fiery red chili baskets. Pots of sour bamboo shoots, crispy gourd vines... stretch throughout the market, featuring green herbs, aromatic herbs, basil, and kinh gioi. Buyers and sellers converge quickly, efficiently, and with satisfaction. The radiant smiles after a fulfilling buying and selling session are the eternal joy of Hang Khoai''s nighttime vegetable market. Everything, absolutely everything, contributes to the well-being and prosperity of Hanoi for the days to come.',
21.03872, 105.84958),
('D2S011', N'D002', N'Nguyen Thien Thuat', N'Nguyen Thien Thuat Street stretches from Hang Khoai Street to Hang Chieu Street, running behind Dong Xuan Market in the northern part of Hanoi. Originally part of Thien Trung village, Hau Tuc district (later renamed Dong Xuan district), in the former Tho Xuong province. The street is 216 meters long and 6 meters wide.
During the French colonial period, in 1928, it was called Rue Lepage. In 1945, it merged with Lataste Street to form Tan Thuat City, which was later renamed Ba Trieu City in 1949. Since 1951, it has been known as Nguyen Thien Thuat Street. Today, the street is located in Dong Xuan Ward, Hoan Kiem District. 
Nguyen Thien Thuat (1844-1926), born in Xuan Duc village, My Hao district (now part of Hai Duong province), obtained his bachelor''s degree in 1871. He held the position of Tán Dương Quân Vụ, hence the nickname Tán Thuật. In 1883, following the signing of the surrender agreement with the French, he was summoned back to Hue but chose to abandon his official position and join the uprising. In 1885, when Hue fell, King Ham Nghi was taken to Quang Binh, and Nguyen Thien Thuat chose Bai Say as his base. Bai Say was a large field covered with tall grass located between Van Giang, Khoai Chau, and My Hao districts (now part of Hung Yen province). Tán Thuật employed guerrilla tactics, ambushing enemy camps and blocking enemy convoys on the Hanoi-Hai Phong and Hanoi-Hung Yen routes, causing significant losses to the enemy forces. By 1888, the French colonial forces launched a fierce suppression campaign. Faced with difficult circumstances, Tán Thuật delegated command to his younger brother Nguyen Thien Ke and general Doc Tit, then traveled to China to seek support from Tôn Thất Thuyết, but the mission was unsuccessful. Later, he fell ill and passed away in Nam Dinh city (Quang Tay).',
21.03812, 105.85061),
('D2S012', N'D002', N'Cao Thang', N'Phố Cao Thắng, with a length of 133 meters and a width of 8 meters, stretches from Trần Nhật Duật Street (house number 26) to Nguyễn Thiện Thuật Street (house number 5) behind Đồng Xuân Market. Originally part of the Nguyên Khiết Thượng village, Tả Túc commune (later renamed Phúc Lâm commune), Thọ Xương district in the past. During the French colonial period, it was known as street number 254 (voie N0254).
In 1928, it was named Rue Grappin. However, in 1949, it was changed to Cao Thắng Street, a name it retains to this day. The street is currently located in Đồng Xuân Ward, Hoàn Kiếm District.
Cao Thắng (1864-1893) was born in Yên Đức village, now part of Sơn Lễ commune, Hương Sơn district, Hà Tĩnh province. In late 1885, during the resistance against the French, alongside Hương Khê, Cao Thắng and his brother Cao Nữu joined the patriotic forces from the early days of the uprising.
In 1887, Phan Đình Phùng traveled to the North to coordinate with anti-French forces, appointing Cao Thắng as the commander-in-chief. Cao Thắng expanded his forces and manufactured additional weapons. He even created guns similar to the French M1874 rifles, earning the admiration of the French themselves.
In 1889, Phan Đình Phùng returned to Hương Khê. Cao Thắng remained the most trusted general of Phan Đình Phùng and directly commanded many battles. On November 21, 1893, during the Battle of Đồn Nu (Thanh Chương district, Nghệ An province), he was hit by a bullet and sacrificed himself at the age of 29.',
21.03869, 105.85096),
('D2S013', N'D002', N'Thanh Ha', N'From Hoan Kiem Lake, strolling through Hàng Ngang, Hàng Đào, reaching Hàng Chiếu, and heading towards Ô Quan Chưởng, one will encounter the small Thanh Hà Street. The street is so diminutive that people often mistake it for an alley nestled amidst the ancient streets. Thanh Hà Street is no longer than 150 meters, starting from Nguyễn Thiện Thuật Street, curving towards Ô Quan Chưởng. In the past, Thanh Hà Street belonged to the Thanh Hà hamlet, under the Hậu Tục district, later changed to Đồng Xuân district in the Thọ Xương province. Today, it is part of Đồng Xuân ward, Hoan Kiem district.
During the French colonial period, Thanh Hà was a narrow alley. In the French map of 1890, it was labeled as Củ Nâu Street, as many families traded forest products brought by boats to the nearby river port. Mr. Trieu Dong, the head of the poetry club in Đồng Xuân ward and one of the few who have lived here the longest, recalls, "My family moved here in 1964. Back then, people referred to it as Thanh Hà alley, not a street like nowadays. It wasn''t until 1986 that Thanh Hà Street had its roads repaved. At that time, this place was mainly populated by laborers.
Today, Thanh Hà Street remains largely unchanged, perhaps busier and more bustling than before. Mr. Lam Tien, a resident of Thanh Hà Street, remembers his childhood, saying, "This alley used to be quite deserted and desolate. The roads during my generation were just gravel, with large stones scattered on the path. This alley is probably very ancient. It wasn''t as bustling as it is now." Despite some road repairs over the years, Thanh Hà Street still retains its original charm, without sidewalks, with numerous small alleys branching off, so narrow that two vehicles cannot pass each other. The houses here are small and quaint, but every house is engaged in business. Some sell fish sauce, others sell vegetables, sweets, or rice. A few houses operate mini hotels, meaning each floor has only one room. From one end to the other, the street is dotted with 3 or 4 travel agency signs offering tours worldwide, primarily catering to Western tourists. Thanh Hà Street is lively from morning until evening, a constant scene of commerce and exchange. The entrance to the street is just wide enough for two motorcycles to pass each other. Here, one feels as if stepping into a marketplace, where both buyers and sellers are neighbors and acquaintances.',
21.03775, 105.85138),
('D2S014', N'D002', N'Dong Xuan', N'Dong Xuan Street stretches approximately 170 meters, connecting to Hang Giay Street at the intersection with Hang Khoai, crossing the intersections with Hang Chieu and Hang Ma, through Gach Alley to Hang Duong Street, facing Hoan Kiem Lake. It belongs to Dong Xuan Ward, Hoan Kiem District. The name Dong Xuan appeared after 1945.
The name Dong Xuan only emerged after the August Revolution. Before that, people still referred to it as Hang Gao Street because the area where Dong Xuan Market was built used to be where farmers carried rice for retail to the local residents. Beans, corn, sweet potatoes, and cassava were sold at Hang Dau and Hang Khoai. Only after 1945 did we change it to Dong Xuan Street.
During the early days of the nationwide resistance war, Dong Xuan Street served as the northwest defensive barrier of Zone I. From the night of December 19, 1946, until early February 1947, the French forces repeatedly attacked this street but failed. By mid-February 1947, the enemy concentrated a large force to attack this "Fortress Market." The battle on February 14, 1947, at Dong Xuan Market forever glorifies the heroic tradition of Hanoi. Hence, on the right side of the market entrance, there is a relief sculpture depicting the symbolic battle.
Today, the street mainly sells clothes, various types of blankets, and serves both adults and children. There are no longer candy stores, only a house in the middle of the street sells glutinous rice cakes for ceremonial purposes, and another famous incense shop at house number 26. On the even-numbered side of the street (from number 2 to number 90), there is a long row in front of the market running a hundred meters; the remaining section has houses on both sides of the street, with two rows of old two-story houses, only a few one-story houses (from number 1 to number 25), and every house is open for business. The land on the odd-numbered side belongs to the former Dong Xuan Ward.
The row of houses on the even-numbered side belongs to the former Phuong Trung village, and the relic of the Phuong Trung communal house is at house number 18 on Dong Xuan Street. The houses on Dong Xuan Street are all ancient, old-fashioned, narrow in width, and many still have loft-style roofs. The houses are not straight; at the market entrance, the sidewalk protrudes onto the road for about three places, a relic of the old pedestrian walkway. From number 26 to number 60, the sidewalk protrudes a few more steps. The place in front of the market entrance has two intersecting paths, and the empty space is still quite large for rice, beans, and market gatherings. 
Today, not only those who trade goods come to Dong Xuan Market, but also many tourists from both inside and outside the country visit and shop at Dong Xuan Market. The market is located right in the Old Quarter, not far from famous souvenir streets and fashion streets, such as Hang Ngang, Hang Dao, Hang Bong, Hang Gai, and close to the Ngoc Son Temple area. It is very convenient for a sightseeing trip in the city center.
Not only is it the most bustling and lively trading place in Hanoi, but Dong Xuan Market also holds many cultural and spiritual values, reflecting the life and activities of the people of the Old Quarter. It is an essential destination for every visitor to Hanoi. As the writer Bang Son said: "Anyone who has the opportunity to visit Hanoi, if they haven''t been to Dong Xuan Market, it''s like only knowing a small part, a tiny corner, or not really having been to Hanoi."',
21.03756, 105.84914),
('D2S015', N'D002', N'Hang Chieu', N'Hang Chieu Street stretches from O Quan Chuong Gate to Hang Ma Street. The street is nearly 280 meters long. According to accounts, back then, the street was narrow and muddy. The houses around Hang Chieu were often thatched and dilapidated. In 1817, the street was widened, leading to the demolition of many houses.
During the temporary occupation, the French colonialists also renamed the street to Giang-duy-puy. This was the name of a spy who doubled as a French smuggler. However, the locals refused to accept this and continued to call it Hang Chieu or "New Street" (meaning the newly opened street). Later, when peace was restored, the street reverted to its original name, Hang Chieu.
Hang Chieu is one of the few rare ancient streets that still preserves and trades in traditional goods according to its name. Scattered along the street, especially as you walk towards the end, the image of straw mats remains prominent. Walking around Hang Chieu, one feels a flood of childhood memories. The image of straw mats with traditional patterns, eye-catching red color, reminiscent of the 90s era, is vivid.
There are many types of mats sold on Hang Chieu, but the most popular is the red mat with the words "Song Hy" printed on it. The bright red letters neatly stand out amidst the mat, evoking childhood memories. In the past, before ink technology advanced, if you bought a new mat and didn''t wash and dry it carefully, it would definitely get dirty. The red ink from the mat would stick to clothes, faces, and limbs, also a childhood memory for many children. The price of this auspicious mat is 430,000 VND per piece.
Here, you can also find nylon mats, bamboo mats, and wooden mats. There is a wide variety of options, from traditional to modern, for consumers to choose from. The prices of mats range from 59,000 VND (office sleeping plastic mats) to the most expensive high-quality straw mats priced at 550,000 VND.
In addition to selling various types of mats, Hang Chieu also offers traditional woven market bags used by old ladies and mothers in the past. These large-sized bags made of rough straw material are familiar images for many Vietnamese people when going to the market.
However, according to shop owners on Hang Chieu, the most profitable items on this street are not the traditional products like straw mats or market bags. The most popular products that attract many consumers to this street are modern fashion woven bags.
These woven bags are smaller, more modern, cute, and environmentally friendly. Therefore, despite only appearing on Hang Chieu in recent years, this product has been loved by many consumers.',
21.03713, 105.85069),
('D2S016', N'D002', N'O Quan Chuong', N'Ô Quan Chưởng Street is a quaint alley nestled in Dong Xuan Ward, Hoan Kiem District, Hanoi. Stretching from Tran Nhat Duat Street to the Quan Chưởng gate, it intersects with Hang Chieu, Dao Duy Tu, and Thanh Ha streets, making it one of the shortest streets in the city.
Named after the historical and cultural landmark, the Quan Chưởng gate located at its end, Ô Quan Chưởng Street holds significance in Hanoi''s rich history. Originally known as Ô Dong Ha, it was one of the five gates built during the 10th year of Canh Hung reign (1749), alongside Phuc Lam, Nhan Hoa, Cau Den, and Cau Dua gates. Over time, it became the only gate that remains standing today.
The street''s name, Ô Quan Chưởng, stems from various legends and historical events. Firstly, it is believed to be named after a retired official named Chưởng Ấn, who built his residence adjacent to the gate. Secondly, during the Nguyen Dynasty, a Chưởng official controlled the gate, requiring all boats passing through to report to him, hence the name. Lastly, during the French invasion of Hanoi in 1873, a Chưởng official and his troops bravely fought and sacrificed their lives at the gate, earning it the moniker Ô Quan Chưởng.
Measuring approximately 75 meters in length and 8-10 meters in width, Ô Quan Chưởng Street is a quiet thoroughfare adorned with only a dozen or so houses and a few modest businesses. Despite its diminutive size, it holds a special place in the hearts of locals and visitors alike, serving as a testament to Hanoi''s enduring history and cultural heritage.',
21.03739, 105.85251),
('D2S017', N'D002', N'Dong Xuan Alley', N'Ngõ Đồng Xuân, also known as Dong Xuan Alley (Hoan Kiem District, Hanoi), stretches a mere 200 meters. This alley is situated right next to the famous market area, not far from Hoan Kiem Lake, making it easily accessible for tourists.
"From around 10 am, this market area starts bustling. Between 11 am to 1 pm, on many days, customers squeeze through, moving about, and eateries are packed, barely getting a break. There are plenty of both Vietnamese and Western customers. Foreign tourists, curious and intrigued, often snap pictures enthusiastically", shared Mrs. Vương Thị Thanh, the owner of a pickled vegetables stall right at the entrance of the alley.
Along the narrow alleyway—barely wide enough to accommodate a row of tables and chairs—the rest of the space is filled with tourists maneuvering around each other, revealing a "culinary maze" with a variety of visually appealing dishes such as spring rolls, shrimp cakes, snail noodles, skewered grilled pork with vermicelli, mixed sweet desserts... What''s special is that the food here is quite cheap. With just a few tens of thousands of dong, tourists can eat to their heart''s content.
The shops here typically only have one stainless steel table and three chairs placed around it. Near the wall, the vendors allocate a small space for cooking stoves, ingredients, spices... Most of the shop owners here have been selling for over a decade, some even for several decades. Many of them have been closely associated with this alley for half of their lives.',
27.03741, 105.8499),
('D2S061', N'D002', N'Bat Dan', N'Bat Dan Street is 248m long, now belongs to Hang Bo and Cua Dong wards, Hoan Kiem district, Hanoi. During the French colonial period, the French changed its name to Rue Vieille des Tasses ("Hang Chen Old Street"). Since 1945, the street has returned to its original name. During the French-Vietnamese war in late 1946 and early 1947, Bat Dan street was seriously destroyed, with only four rooftops remaining at the top of the street. During the temporary occupation, the street was restored and repaired. Today, Bat Dan street has become a bustling and luxurious trading place of the old town. Recently, a gold-plated pottery shop opened. No. 49 Bat Dan is a small restaurant, with the same tables and chairs from half a century ago, but famous for its heirloom pho. There are some interesting things to eat there, delicious pho noodles, fresh and fragrant rare beef, sweet broth with the taste of stewed bones, just like traditional Hanoi pho.',
21.033936901691675, 105.84694630912736),
('D2S062', N'D002', N'Hang Bo', N'Hang Bo Street is 270m long, now belongs to Hang Bo ward, Hoan Kiem district, Hanoi. Hang Bo Street was formed very long ago, connecting the Dong Thanh area with the old dyke at the beginning of Hang Dao Street. At the end of the 19th century, Hang Bo street was called Hang Dep and used to have shops selling clogs and sandals. A few decades passed, many households began weaving bamboo baskets, and during Tet, the streets were filled with buyers and sellers, because people from other provinces came to Hanoi to store goods and needed baskets to store them. In the past, near the Lunar New Year, on the sidewalks of Hang Bo Street, there were many vendors displaying Chinese ink and red paper to write letters to celebrate the new spring. Hang Bo Street today has changed dramatically with high-rise buildings and households also selling many other products. But small shops are still scattered here and there, attracting crowds of buyers and tourists to visit.',
21.034120915362564, 105.849259195635),
('D2S063', N'D002', N'Hang Bac', N'Hang Bac Street has a length of 330m, located right in Hang Bac ward, Hoan Kiem district, Hanoi. From here you can easily move to Hoan Kiem Lake in just about 10 - 15 minutes in the North direction. People have known the name Hang Bac Street since the Le Dynasty, around the 15th century. Until the Nguyen Dynasty, this street was home to many famous jewelers. .This is a central street. Hang Bac Street is convenient to everything in Hanoi, a short walk from the main shops, the lake, the night market, some famous restaurants, some tourist attractions shops, everything. And of course the silver jewelry stores, lots of great quality jewelry stores. The hardest thing is deciding which jewelry to buy. Gem and gold shops are also located on this street. This is what makes people identify the origin of jewelry on Hang Bac Street. A unique feature that is hard to mistake.',
21.03412865953434, 105.85207278214253),
('D2S064', N'D002', N'Hang Mam', N'Hang Mam Street is 188m long and 7m wide. From Tran Nhat Duat street to Hang Bac street at Ma May intersection, crossing Nguyen Huu Huan street. Fish street in the past specialized in selling fish sauce and other aquatic products and eggs. During the French colonial period, the street was named Fish Sauce Row (Rue de la Saumure). The old name of Hang Mam street was officially reused by the mayor of Hanoi, doctor Tran Van Lai, in 1945. The construction of the Chuong Duong bridge made the area close to the north of Hang Mam street become a transportation hub. important information of Hanoi. Currently, fish sauce is no longer sold here, but the main products are tombstones, crockery, and earthenware. Coming to Hanoi, visitors should spend a whole day walking around the streets here, to immerse themselves in the market atmosphere, and understand more about the identity and culture of Vietnamese people.',
21.034019409702786, 105.85474461302874),
('D2S065', N'D002', N'Hang Tre', N'Hang Tre Street is 306m long and 8m wide. From Hang Mam street to Lo Su street, cross Bach Thai Buoi alley and Hang Thung street. The street name dates back to before the French colonial period. After that, the French called it "rue des Bambous". In 1945, it regained the Vietnamese name of Hang Tre street. In the past, because this street was right next to the Red River, convenient for loading and unloading bamboo, there were "stalls" selling bamboo here, hence the name. Today, on the first part of Hang Tre street, there are many shops that upgrade car interiors, wash cars, change oil, maintain and apply plastic stickers for cars and motorbikes. The street has been expanded, the strongest are the food shops: draft beer, fish cakes, rice cakes, peanuts, vermicelli, wine, coffee, hot pot, pho... popular, delicious, cheap. Around the intersection of Hang Tre - Lo Su - Hang Voi streets, there are still almost intact monumental French colonial-style architectural works built more than a hundred years ago.',
21.032712761438493, 105.85552322447074),
('D2S066', N'D002', N'Nguyen Huu Huan', N'Nguyen Huu Huan Street is 448m long and 12m wide. Nguyen Huu Huan Street starts from Tran Nhat Duat Street to Lo Su Street, cutting through Hang Mam and Hang Thung streets. Before 1890, the French called it De street (rue de la Digue). Few people know that this place used to be a riverbank, the breakwater was located right on the current road, so at the beginning of the French colonial period, this street used to have that name. The last street name was given in June 1964. Nguyen Huu Huan street also has a memorable house. That is house number 12, which in 1930 was the secret headquarters of the Hanoi Party Committee. Here, comrade Nguyen Ngoc Vu was then Secretary of the City Party Committee, working from June 1930 to December 1930. Nguyen Huu Huan Street currently has wide sidewalks, tall shady trees and many bus routes passing by.',
21.033292158737517, 105.85448468214247),
('D2S067', N'D002', N'Hang Be', N'Hang Be street is 172m long, 6m wide, connecting Hang Mam street to the intersection of Hang Dau - Cau Go street. According to records, Hang Be street was formerly part of the old Red River dyke. When the flow is still close to the foot of the dyke, rafts of wood, cork, bamboo, rattan, and bamboo leaves from up and down the region often come here to bring to the market for consumption, so this part of the dyke is called Hang Be. Previously, Hang Be street was known to many people because there was Hang Be market here. Hang Be Market consists of only rows of tents set up in the middle of the old town. It was originally a temporary tent-style market right on the street and sidewalk, selling all kinds of essential goods at affordable prices. Entering the 21st century, the Hanoi People''s Committee decided to clear Hang Be market so that Gia Ngu street could be transformed into a walking street and sell souvenirs to serve tourists. Hang Be as well as surrounding streets are gradually changing with the development of the city.',
21.033294872746318, 105.8537631802915),
('D2S068', N'D002', N'Dinh Tien Hoang', N'Dinh Tien Hoang Street is 900m long and 16m wide. From Dong Kinh Nghia Thuc Square (at the beginning of Hang Dao and Hang Gai streets), running around the north and east banks of Hoan Kiem Lake, to the intersection of Trang Tien - Hang Khay - Hang Bai. During the French colonial period, the street was called Francis Garnier Avenue. In 1945, Hanoi Governor - Doctor Tran Van Lai changed the street''s name to Dinh Tien Hoang to remember the Emperor''s merits in ending the feud and unifying the country. Dinh Tien Hoang Street located on the east side of Hoan Kiem Lake is considered by many historians and writers to be one of the few places where thousands of years of sacred energy converge in Thang Long - Hanoi. Besides the green Sword Lake in all seasons with the ancient Turtle Tower, along the street there are also tourist attractions including: Hoa Phong Tower (relics of Bao An Pagoda); Flower garden and statue of Ly Thai To; Ba Kieu Temple and Soldier Monument: No. 59 Dinh Tien Hoang; Ngoc Son Temple with Pen Tower, Dai Nghien and The Huc Bridge; Dong Kinh Nghia Thuc Square.',
21.02893174498158, 105.85377452447071),
('D2S069', N'D002', N'Le Thai To', N'Le Thai To Street is 690m long, located in Hang Trong ward, Hoan Kiem district, Hanoi. The north connects Hang Dao street at the intersection of Hang Gai - Cau Go and then goes along the west bank of Hoan Kiem Lake through the beginning of Dinh Tien Hoang, Luong Van Can, Bao Khanh, Hang Trong streets; The last section connects Ba Trieu street at the intersection of Trang Thi - Hang Khay. Le Thai To Street is a one-way street, although long, it is quite convenient for tourists with spacious sidewalks and many buses passing by or with stops nearby. In addition to Dong Kinh Nghia Thuc Square, not far from the old house of Mr. Luong Van Can''s family, on the first part of the street is the headquarters of Nhan Dan newspaper, large banks and companies, along with entertainment places and restaurants. famous for a long time. Up to now, the facade of the new Hanoi Newspaper headquarters still retains almost intact the architectural style of more than a century ago. Therefore, this place has become one of the check-in points for many young people and tourists when coming to Hanoi.',
21.0289249678572, 105.851370832261),
('D2S070', N'D002', N'Hang Khay', N'Hang Khay Street is a short street, the street section from Hang Bai - Trang Tien intersection to Ba Trieu - Trang Thi intersection is just over 100m long, formerly known as Tho Kham street. First, inlaid objects were favored by urban people and noble families. Chairs, tables, mahogany cabinets, and tea cabinets are inlaid with mother-of-pearl, quite beautiful. Mosaic workers inlay flowers and birds, creating beauty for every piece of furniture. Although the street is short, there was also a temple to worship the ancestors of the craft. Many people believe that the origin of the mosaic craft came from Thanh Hoa, with its founder being Nguyen Kim. Since the capital''s liberation, October 1954, the street had a new name: Hang Khay street. The street has the characteristics of only one row of odd-numbered houses located south of Hoan Kiem Lake. In the center of the capital, Hang Khay street has become a "historical witness": High-level delegations and heads of state from many countries visiting Vietnam all pass through Hang Khay to return to the Government Guest House, Metropole Hotel, Opera House. Today, the most popular items on Hang Khay Street are still shops promoting the traditional craft of "mother-of-pearl wood" sold in galleries with a variety of designs.',
21.0257127551758, 105.852282411852),
('D2S071', N'D002', N'Trang Tien', N'Trang Tien Street is located right in the center of Hanoi, one of the busiest and most vibrant streets in Hanoi. If you don''t know which ward Trang Tien street belongs to, this 708m long street belongs to Trang Tien ward, Hoan Kiem district, Hanoi. Trang Tien Street starts from Hoan Kiem Lake, through Hang Khay to Hanoi Opera House. Previously, Trang Tien street was a long road, the west bordered Lord Trinh''s palace, the east bordered Tay Long square or today''s Hanoi Opera House, connecting to Dong Thuy base and Red River wharf. In 1808, King Gia Long established a money factory here, called Bao Tuyen Cuc. From 1954 onwards, these streets were merged together into Trang Tien city as it is today. With a prime location, Trang Tien street is a familiar destination for Hanoians and a unique tourist discovery destination for tourists from all over.',
21.0244063601426, 105.857001144027),
('D2S072', N'D002', N'Nha Chung', N'Nha Chung Street is about 300m long, located in Hang Trong ward, Hoan Kiem district, Hanoi. The north continues on Ly Quoc Su street and borders Nha Tho street at Notre Dame Square, the south borders Quang Trung street and flows to Trang Thi intersection. During the French colonial period, the street was called Rue de la Mission (Mission Society Street, or Mission Society Street). In 1925, the Vatican established the Apostolic Nunciature in Vietnam and built it right on this land of Nha Chung Street. On Nha Chung street today, there are Catholic facilities such as the Cathedral, headquarters of the Vietnam Catholic Bishops Conference, next to a large park and the Library.',
21.0288342804488, 105.849132768316),
('D2S073', N'D002', N'Ly Quoc Su', N'Ly Quoc Su Street from Hang Bong - Hang Manh intersection to Nha Tho - Nha Chung intersection is 244m long, now belongs to Hang Trong ward, Hoan Kiem district, Hanoi. During the French colonial period, this street was called Rue Lamblot. The Cathedral was built in the late 19th century on the foundation of the old Bao Thien pagoda on the south side of Au Trieu street now. At noon on October 6, 1972, American planes fired missiles at houses No. 37 and 39B, killing many people. Immediately afterwards, on the wall in front of house 39B, there was a sign recording this crime. In the 1980s, the famous specialty restaurant Nguyen Sinh from Thuoc Bac street moved to 17 Ly Quoc Su street. In addition, house number 43 was the last residence for a very long time of Hoang Cam - a poet from Kinh Bac.',
21.029791875791, 105.849162708085),
('D2S074', N'D002', N'Ngo Quyen', N'Ngo Quyen Street is 1,220m long and 14m wide. The street extends from Hang Voi street to Ham Long street, running across Ly Thai To, Le Lai, Trang Tien, Hai Ba Trung, Ly Thuong Kiet, and Tran Hung Dao streets. During the French colonial period in 1892, the avenue was named Hangri Rivie (Boulevard Henri Rivie), and in 1945 it was changed to Ngo Quyen city. Old relics in the street include Kiem Ho communal house, now at 7 Hang Voi, and Ham Long pagoda of the old Ham Chau village, now in lane 20, Ham Long street. If Tran Hung Dao street is a street of rows of crocodile trees, then Ngo Quyen street is a street of rows of tamarind trees, so throwing tamarind and climbing tamarind is also a game of previous generation students.',
21.0244233910202, 105.854988586047),
('D2S075', N'D002', N'Hang Bai', N'Hang Bai Street is 616m long and 14m wide. From the end of Dinh Tien Hoang street (shore of Sword Lake) to the intersection of Hue - Ham Long streets, crossing Hai Ba Trung, Ly Thuong Kiet, and Tran Hung Dao streets. During temporary occupation, the French called this street rue des Cartes, later changed it to Dong Khanh Avenue (boulevard Dong Khanh), in 1945 it was renamed Trieu Quang Phuc city, in 1949 - 1951 it was renamed Dong Khanh Avenue. After peace, the old town was renamed Hang Bai. It''s called Hang Bai because there was a time at the beginning of the street where there were shops selling decks of cards, such as tom''s nest and tam chrysanthemum. This street is located in an expanded area from the early years of the French colonial period. Today, the prominent item sold on the street is audio equipment, with a wide variety of models, serving everyone from ordinary people to "rich" people.',
21.022563353581, 105.852572200885)

/*Image*/
INSERT [dbo].[tStreet_Image] ([ImageID], [StreetID], [ImageURL]) VALUES 
('Chua_Lang_Street_1', 'D1S031', 'Chua_Lang_Street_1.jpg'),
('Chua_Lang_Street_2', 'D1S031', 'Chua_Lang_Street_2.jpg'),
('Chua_Lang_Street_3', 'D1S031', 'Chua_Lang_Street_3.jpg'),

('Huynh_Thuc_Khang_Street_1', 'D1S032', 'Huynh_Thuc_Khang_Street_1.jpg'),
('Huynh_Thuc_Khang_Street_2', 'D1S032', 'Huynh_Thuc_Khang_Street_2.jpg'),
('Huynh_Thuc_Khang_Street_3', 'D1S032', 'Huynh_Thuc_Khang_Street_3.jpg'),

('Phao_Dai_Lang_Street_1', 'D1S033', 'Phao_Dai_Lang_Street_1.jpg'),
('Phao_Dai_Lang_Street_2', 'D1S033', 'Phao_Dai_Lang_Street_2.jpg'),
('Phao_Dai_Lang_Street_3', 'D1S033', 'Phao_Dai_Lang_Street_3.jpg'),

('Kim_Ma_Street_1', 'D1S001', 'Kim_Ma_Street_1.jpg'),
('Kim_Ma_Street_2', 'D1S001', 'Kim_Ma_Street_2.jpg'),
('Kim_Ma_Street_3', 'D1S001', 'Kim_Ma_Street_3.png'),

('La_Thanh_Street_1', 'D1S002', 'La_Thanh_Street_1.jpg'),
('La_Thanh_Street_2', 'D1S002', 'La_Thanh_Street_2.jpg'),
('La_Thanh_Street_3', 'D1S002', 'La_Thanh_Street_3.png'),

('Dao_Tan_Street_1', 'D1S003', 'Dao_Tan_Street_1.jpg'),
('Dao_Tan_Street_2', 'D1S003', 'Dao_Tan_Street_2.jpg'),
('Dao_Tan_Street_3', 'D1S003', 'Dao_Tan_Street_3.jpg'),

('Buoi_Street_1', 'D1S004', 'Buoi_Street_1.jpg'),
('Buoi_Street_2', 'D1S004', 'Buoi_Street_2.jpg'),
('Buoi_Street_3', 'D1S004', 'Buoi_Street_3.jpg'),

('Pham_Huy_Thong_Street_1', 'D1S005', 'Pham_Huy_Thong_Street_1.jpg'),
('Pham_Huy_Thong_Street_2', 'D1S005', 'Pham_Huy_Thong_Street_2.jpg'),
('Pham_Huy_Thong_Street_3', 'D1S005', 'Pham_Huy_Thong_Street_3.jpg'),

('Nguyen_Chi_Thanh_Street_1', 'D3S001', 'Nguyen_Chi_Thanh_Street_1.jpg'),
('Nguyen_Chi_Thanh_Street_2', 'D3S001', 'Nguyen_Chi_Thanh_Street_2.jpg'),
('Nguyen_Chi_Thanh_Street_3', 'D3S001', 'Nguyen_Chi_Thanh_Street_3.jpg'),

('HangDau_Street_1', 'D2S001', 'HangDau_Street_1.jpg'),
('HangDau_Street_2', 'D2S001', 'HangDau_Street_2.jpg'),
('HangDau_Street_3', 'D2S001', 'HangDau_Street_3.jpg'),
('HangDau_Street_4', 'D2S001', 'HangDau_Street_4.jpg'),
('HangDau_Street_5', 'D2S001', 'HangDau_Street_5.jpg'),
('HangDau_Street_6', 'D2S001', 'HangDau_Street_6.jpg'),
('HangDau_Street_7', 'D2S001', 'HangDau_Street_7.jpg'),

('PhungHung_Street_1', 'D2S002', 'PhungHung_Street_1.jpg'),
('PhungHung_Street_2', 'D2S002', 'PhungHung_Street_2.jpg'),
('PhungHung_Street_3', 'D2S002', 'PhungHung_Street_3.jpg'),
('PhungHung_Street_4', 'D2S002', 'PhungHung_Street_4.jpg'),
('PhungHung_Street_5', 'D2S002', 'PhungHung_Street_5.jpg'),

('HangCot_Street_1', 'D2S003', 'HangCot_Street_1.jpg'),
('HangCot_Street_2', 'D2S003', 'HangCot_Street_2.jpg'),
('HangCot_Street_3', 'D2S003', 'HangCot_Street_3.jpg'),
('HangCot_Street_4', 'D2S003', 'HangCot_Street_4.jpg'),

('HangGiay_Street_1', 'D2S004', 'HangGiay_Street_1.jpg'),
('HangGiay_Street_2', 'D2S004', 'HangGiay_Street_2.jpg'),
('HangGiay_Street_3', 'D2S004', 'HangGiay_Street_3.jpg'),
('HangGiay_Street_4', 'D2S004', 'HangGiay_Street_4.jpg'),
('HangGiay_Street_5', 'D2S004', 'HangGiay_Street_5.jpg'),
('HangGiay_Street_6', 'D2S004', 'HangGiay_Street_6.jpg'),
('HangGiay_Street_7', 'D2S004', 'HangGiay_Street_7.jpg'),
('HangGiay_Street_8', 'D2S004', 'HangGiay_Street_8.jpg'),

('NguyenThiep_Street_1', 'D2S005', 'NguyenThiep_Street_1.jpg'),
('NguyenThiep_Street_2', 'D2S005', 'NguyenThiep_Street_2.jpg'),

('GamCau_Street_1', 'D2S006', 'GamCau_Street_1.jpg'),
('GamCau_Street_2', 'D2S006', 'GamCau_Street_2.jpg'),
('GamCau_Street_3', 'D2S006', 'GamCau_Street_3.jpg'),
('GamCau_Street_4', 'D2S006', 'GamCau_Street_4.jpg'),

('TranNhatDuat_Street_1', 'D2S007', 'TranNhatDuat_Street_1.jpg'),
('TranNhatDuat_Street_2', 'D2S007', 'TranNhatDuat_Street_2.jpg'),
('TranNhatDuat_Street_3', 'D2S007', 'TranNhatDuat_Street_3.jpg'),
('TranNhatDuat_Street_4', 'D2S007', 'TranNhatDuat_Street_4.jpg'),

('HangLuoc_Street_1', 'D2S008', 'HangLuoc_Street_1.jpg'),
('HangLuoc_Street_2', 'D2S008', 'HangLuoc_Street_2.jpg'),
('HangLuoc_Street_3', 'D2S008', 'HangLuoc_Street_3.jpg'),
('HangLuoc_Street_4', 'D2S008', 'HangLuoc_Street_4.jpg'),
('HangLuoc_Street_5', 'D2S008', 'HangLuoc_Street_5.jpg'),
('HangLuoc_Street_6', 'D2S008', 'HangLuoc_Street_6.jpg'),

('HangChai_Street_1', 'D2S009', 'HangChai_Street_1.jpg'),
('HangChai_Street_2', 'D2S009', 'HangChai_Street_2.jpg'),
('HangChai_Street_3', 'D2S009', 'HangChai_Street_3.jpg'),
('HangChai_Street_4', 'D2S009', 'HangChai_Street_4.jpg'),
('HangChai_Street_5', 'D2S009', 'HangChai_Street_5.jpg'),
('HangChai_Street_6', 'D2S009', 'HangChai_Street_6.jpg'),
('HangChai_Street_7', 'D2S009', 'HangChai_Street_7.jpg'),

('HangKhoai_Street_1', 'D2S010', 'HangKhoai_Street_1.jpg'),
('HangKhoai_Street_2', 'D2S010', 'HangKhoai_Street_2.jpg'),
('HangKhoai_Street_3', 'D2S010', 'HangKhoai_Street_3.jpg'),
('HangKhoai_Street_4', 'D2S010', 'HangKhoai_Street_4.jpg'),
('HangKhoai_Street_5', 'D2S010', 'HangKhoai_Street_5.jpg'),

('NguyenThienThuat_Street_1', 'D2S011', 'NguyenThienThuat_Street_1.jpg'),
('NguyenThienThuat_Street_2', 'D2S011', 'NguyenThienThuat_Street_2.jpg'),
('NguyenThienThuat_Street_3', 'D2S011', 'NguyenThienThuat_Street_3.jpg'),
('NguyenThienThuat_Street_4', 'D2S011', 'NguyenThienThuat_Street_4.jpg'),
('NguyenThienThuat_Street_5', 'D2S011', 'NguyenThienThuat_Street_5.jpg'),

('CaoThang_Street_1', 'D2S012', 'CaoThang_Street_1.jpg'),
('CaoThang_Street_2', 'D2S012', 'CaoThang_Street_2.jpg'),

('ThanhHa_Street_1', 'D2S013', 'ThanhHa_Street_1.jpg'),
('ThanhHa_Street_2', 'D2S013', 'ThanhHa_Street_2.jpg'),
('ThanhHa_Street_3', 'D2S013', 'ThanhHa_Street_3.jpg'),

('DongXuan_Street_1', 'D2S014', 'DongXuan_Street_1.jpg'),
('DongXuan_Street_2', 'D2S014', 'DongXuan_Street_2.jpg'),
('DongXuan_Street_3', 'D2S014', 'DongXuan_Street_3.jpg'),

('HangChieu_Street_1', 'D2S015', 'HangChieu_Street_1.jpg'),
('HangChieu_Street_2', 'D2S015', 'HangChieu_Street_2.jpg'),
('HangChieu_Street_3', 'D2S015', 'HangChieu_Street_3.jpg'),
('HangChieu_Street_4', 'D2S015', 'HangChieu_Street_4.jpg'),
('HangChieu_Street_5', 'D2S015', 'HangChieu_Street_5.jpg'),
('HangChieu_Street_6', 'D2S015', 'HangChieu_Street_6.jpg'),
('HangChieu_Street_7', 'D2S015', 'HangChieu_Street_7.jpg'),
('HangChieu_Street_8', 'D2S015', 'HangChieu_Street_8.jpg'),

('OQuanChuong_Street_1', 'D2S016', 'OQuanChuong_Street_1.jpg'),
('OQuanChuong_Street_2', 'D2S016', 'OQuanChuong_Street_2.jpg'),
('OQuanChuong_Street_3', 'D2S016', 'OQuanChuong_Street_3.jpg'),
('OQuanChuong_Street_4', 'D2S016', 'OQuanChuong_Street_4.jpg'),

('DongXuanAlley_Street_1', 'D2S017', 'DongXuanAlley_Street_1.jpg'),
('DongXuanAlley_Street_2', 'D2S017', 'DongXuanAlley_Street_2.jpg'),
('DongXuanAlley_Street_3', 'D2S017', 'DongXuanAlley_Street_3.jpg'),
('DongXuanAlley_Street_4', 'D2S017', 'DongXuanAlley_Street_4.jpg'),
('DongXuanAlley_Street_5', 'D2S017', 'DongXuanAlley_Street_5.jpg'),
('DongXuanAlley_Street_6', 'D2S017', 'DongXuanAlley_Street_6.jpg'),
('DongXuanAlley_Street_7', 'D2S017', 'DongXuanAlley_Street_7.jpg'),

('Bat_Dan_Street_1', 'D2S061', 'Bat_Dan_Street_1.jpg'),
('Bat_Dan_Street_2', 'D2S061', 'Bat_Dan_Street_2.jpg'),
('Bat_Dan_Street_3', 'D2S061', 'Bat_Dan_Street_3.jpg'),

('Hang_Bo_Street_1', 'D2S062', 'Hang_Bo_Street_1.jpg'),
('Hang_Bo_Street_2', 'D2S062', 'Hang_Bo_Street_2.jpg'),
('Hang_Bo_Street_3', 'D2S062', 'Hang_Bo_Street_3.jpg'),

('Hang_Bac_Street_1', 'D2S063', 'Hang_Bac_Street_1.jpg'),
('Hang_Bac_Street_2', 'D2S063', 'Hang_Bac_Street_2.jpg'),
('Hang_Bac_Street_3', 'D2S063', 'Hang_Bac_Street_3.jpg'),

('Hang_Mam_Street_1', 'D2S064', 'Hang_Mam_Street_1.jpg'),
('Hang_Mam_Street_2', 'D2S064', 'Hang_Mam_Street_2.jpg'),
('Hang_Mam_Street_3', 'D2S064', 'Hang_Mam_Street_3.jpg'),
('Hang_Mam_Street_4', 'D2S064', 'Hang_Mam_Street_4.jpg'),

('Hang_Tre_Street_1', 'D2S065', 'Hang_Tre_Street_1.jpg'),
('Hang_Tre_Street_2', 'D2S065', 'Hang_Tre_Street_2.jpg'),
('Hang_Tre_Street_3', 'D2S065', 'Hang_Tre_Street_3.jpg'),
('Hang_Tre_Street_4', 'D2S065', 'Hang_Tre_Street_4.jpg'),
('Hang_Tre_Street_5', 'D2S065', 'Hang_Tre_Street_5.jpg'),

('Nguyen_Huu_Huan_Street_1', 'D2S066', 'Nguyen_Huu_Huan_Street_1.jpg'),
('Nguyen_Huu_Huan_Street_2', 'D2S066', 'Nguyen_Huu_Huan_Street_2.jpg'),
('Nguyen_Huu_Huan_Street_3', 'D2S066', 'Nguyen_Huu_Huan_Street_3.jpg'),
('Nguyen_Huu_Huan_Street_4', 'D2S066', 'Nguyen_Huu_Huan_Street_4.jpg'),
('Nguyen_Huu_Huan_Street_5', 'D2S066', 'Nguyen_Huu_Huan_Street_5.jpg'),

('Hang_Be_Street_1', 'D2S067', 'Hang_Be_Street_1.jpg'),
('Hang_Be_Street_2', 'D2S067', 'Hang_Be_Street_2.jpg'),
('Hang_Be_Street_3', 'D2S067', 'Hang_Be_Street_3.jpg'),
('Hang_Be_Street_4', 'D2S067', 'Hang_Be_Street_4.jpg'),

('Dinh_Tien_Hoang_Street_1', 'D2S068', 'Dinh_Tien_Hoang_Street_1.jpg'),
('Dinh_Tien_Hoang_Street_2', 'D2S068', 'Dinh_Tien_Hoang_Street_2.jpg'),
('Dinh_Tien_Hoang_Street_3', 'D2S068', 'Dinh_Tien_Hoang_Street_3.jpg'),
('Dinh_Tien_Hoang_Street_4', 'D2S068', 'Dinh_Tien_Hoang_Street_4.jpg'),
('Dinh_Tien_Hoang_Street_5', 'D2S068', 'Dinh_Tien_Hoang_Street_5.jpg'),

('Le_Thai_To_Street_1', 'D2S069', 'Le_Thai_To_Street_1.jpg'),
('Le_Thai_To_Street_2', 'D2S069', 'Le_Thai_To_Street_2.jpg'),
('Le_Thai_To_Street_3', 'D2S069', 'Le_Thai_To_Street_3.jpg'),
('Le_Thai_To_Street_4', 'D2S069', 'Le_Thai_To_Street_4.jpg'),
('Le_Thai_To_Street_5', 'D2S069', 'Le_Thai_To_Street_5.jpg'),

('Hang_Khay_Street_1', 'D2S070', 'Hang_Khay_Street_1.jpg'),
('Hang_Khay_Street_2', 'D2S070', 'Hang_Khay_Street_2.jpg'),
('Hang_Khay_Street_3', 'D2S070', 'Hang_Khay_Street_3.jpg'),
('Hang_Khay_Street_4', 'D2S070', 'Hang_Khay_Street_4.jpg'),
('Hang_Khay_Street_5', 'D2S070', 'Hang_Khay_Street_5.jpg'),

('Trang_Tien_Street_1', 'D2S071', 'Trang_Tien_Street_1.jpg'),
('Trang_Tien_Street_2', 'D2S071', 'Trang_Tien_Street_2.jpg'),
('Trang_Tien_Street_3', 'D2S071', 'Trang_Tien_Street_3.jpg'),
('Trang_Tien_Street_4', 'D2S071', 'Trang_Tien_Street_4.jpg'),
('Trang_Tien_Street_5', 'D2S071', 'Trang_Tien_Street_5.jpg'),

('Nha_Chung_Street_1', 'D2S072', 'Nha_Chung_Street_1.jpg'),
('Nha_Chung_Street_2', 'D2S072', 'Nha_Chung_Street_2.jpg'),
('Nha_Chung_Street_3', 'D2S072', 'Nha_Chung_Street_3.jpg'),
('Nha_Chung_Street_4', 'D2S072', 'Nha_Chung_Street_4.jpg'),
('Nha_Chung_Street_5', 'D2S072', 'Nha_Chung_Street_5.jpg'),

('Ly_Quoc_Su_Street_1', 'D2S073', 'Ly_Quoc_Su_Street_1.jpg'),
('Ly_Quoc_Su_Street_2', 'D2S073', 'Ly_Quoc_Su_Street_2.jpg'),
('Ly_Quoc_Su_Street_3', 'D2S073', 'Ly_Quoc_Su_Street_3.jpg'),
('Ly_Quoc_Su_Street_4', 'D2S073', 'Ly_Quoc_Su_Street_4.jpg'),
('Ly_Quoc_Su_Street_5', 'D2S073', 'Ly_Quoc_Su_Street_5.jpg'),

('Ngo_Quyen_Street_1', 'D2S074', 'Ngo_Quyen_Street_1.jpg'),
('Ngo_Quyen_Street_2', 'D2S074', 'Ngo_Quyen_Street_2.jpg'),
('Ngo_Quyen_Street_3', 'D2S074', 'Ngo_Quyen_Street_3.jpg'),
('Ngo_Quyen_Street_4', 'D2S074', 'Ngo_Quyen_Street_4.jpg'),
('Ngo_Quyen_Street_5', 'D2S074', 'Ngo_Quyen_Street_5.jpg'),

('Hang_Bai_Street_1', 'D2S075', 'Hang_Bai_Street_1.jpg'),
('Hang_Bai_Street_2', 'D2S075', 'Hang_Bai_Street_2.jpg'),
('Hang_Bai_Street_3', 'D2S075', 'Hang_Bai_Street_3.jpg'),
('Hang_Bai_Street_4', 'D2S075', 'Hang_Bai_Street_4.jpg'),
('Hang_Bai_Street_5', 'D2S075', 'Hang_Bai_Street_5.jpg')
